### PR TITLE
update rollup config and minify script

### PR DESCRIPTION
**Pull request by zhangqiangoffice**
Maybe you are busy with other things, so I updated the rollup configuration file by myself, and rebuild the dist files.

### CODE REVIEW

**Comment by tikiatua** [comment]
Hi @zhangqiangoffice 

Thank you for your help. I am currently really busy with some other projects.

**Comment by zhangqiangoffice** [comment]
You are welcome！Can I be a contributor to this project？I mean, put my name in the list of contributors.

**Comment by tikiatua** [comment]
Hi @zhangqiangoffice,

This should automatically have happened, when I merged your commits into the master branch. Not sure why your name does not show up in the contributors list

**Comment by zhangqiangoffice** [comment]
Hi @tikiatua ,
It doesn't matter. That may take some time. I will continue to contribute to the code.

**Comment by zhangqiangoffice** [comment]
Indeed, There were something wrong in the workflow of my pull request(The user.email of git config should be as same as the github.com account). So, I make a new pull request today, and verify this problem by the way.

**Pull request merged**
